pipeline:
  name: Build pr-demo
  identifier: Build_clddevsecops_pr_demo_1727357751485
  projectIdentifier: demoharness
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
                  description: Simple msg
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1727350968474
        repoName: clddevsecops/pr-demo
        build: <+input>
