pipeline:
  name: Build PR-Demo Enhanced with Maven Setup
  identifier: Build_clddevsecops_pr_demo_1727357751485
  projectIdentifier: demoharness
  orgIdentifier: default
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Maven
                  identifier: Install_Maven
                  description: Install Maven on the build environment
                  spec:
                    shell: Sh
                    command: |
                      echo "Installing Maven..."
                      apt-get update && apt-get install -y maven
                      echo "Maven installed successfully."
              - step:
                  type: Run
                  name: Compile Code
                  identifier: Compile_Code
                  description: Compile project code
                  spec:
                    shell: Sh
                    command: |
                      echo "Starting the build process..."
                      mvn clean compile
                      echo "Build process completed successfully!"
              - step:
                  type: Run
                  name: Run Unit Tests
                  identifier: Run_Unit_Tests
                  description: Run unit tests on the code
                  spec:
                    shell: Sh
                    command: |
                      echo "Running unit tests..."
                      mvn test
                      echo "Unit tests completed."
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Test Stage
        identifier: Test_Stage
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Static Code Analysis
                  identifier: Static_Code_Analysis
                  description: Perform static code analysis (e.g., SonarQube)
                  spec:
                    shell: Sh
                    command: |
                      echo "Running static code analysis..."
                      # Add your actual static analysis command
                      echo "Static code analysis completed."
              - step:
                  type: Run
                  name: Integration Tests
                  identifier: Integration_Tests
                  description: Run integration tests
                  spec:
                    shell: Sh
                    command: |
                      echo "Running integration tests..."
                      mvn verify
                      echo "Integration tests completed."
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Deploy Stage
        identifier: Deploy_Stage
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Deploy to Staging
                  identifier: Deploy_to_Staging
                  description: Deploy to the staging environment
                  spec:
                    shell: Sh
                    command: |
                      echo "Deploying to staging environment..."
                      kubectl apply -f deployment.yaml
                      echo "Deployment to staging completed."
              - step:
                  type: Run
                  name: Run Smoke Tests
                  identifier: Run_Smoke_Tests
                  description: Run post-deployment smoke tests
                  spec:
                    shell: Sh
                    command: |
                      echo "Running smoke tests on staging..."
                      # Add commands for smoke tests
                      echo "Smoke tests completed."
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1727350968474
        repoName: clddevsecops/pr-demo
        build: <+input>
