name: Demo to create automatic PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: "CLT-${{ github.sha }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Create feature branch
        run: |
          git checkout -b $BRANCH_NAME
          echo "Created and checked out to branch $BRANCH_NAME"
          git branch -vv  # Debugging: Verify the branch tracking information

      - name: Commit changes
        run: |
          git add AUTHOR
          git commit -m "Update author information"
          git push origin $BRANCH_NAME

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Apply Prettier formatting"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      # - name: Approve Pull Request1
      #   uses: juliangruber/approve-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.APPROVER_DEMO }}
      #     number: ${{ steps.demo-1.outputs.pull-request-number }}

      # - name: Merge Pull request1
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.demo-1.outputs.pull-request-number }}
      #     method: squash

      # - name: Update author information again
      #   run: echo Gaurav > AUTHOR

      # - name: Raise PR 2
      #   id: demo-2
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch: "auto-pr-branch2"
      #     base: main
      #     title: "demo for auto pr2"
      #     committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
      #     author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
      #     body:
      #       This is to show automatic PR creation
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     delete-branch: true

      # - name: Approve Pull Request2
      #   uses: juliangruber/approve-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.demo-2.outputs.pull-request-number }}

      # - name: Merge Pull request2
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.demo-2.outputs.pull-request-number }}
      #     method: squash


