name: Demo to create automatic PR

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # This line gives the workflow write permissions
  pull-requests: write  # This line gives the workflow pull request permissions
  
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: "feature/prettier-${{ github.sha }}"
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Create feature branch
        if: ${{ steps.files.outputs.has_files == 'true' }}
        run: |
          git checkout -b $BRANCH_NAME
          echo "Created and checked out to branch $BRANCH_NAME"
          git branch -vv  # Debugging: Verify the branch tracking information

      - name: Raise PR 1
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "demo for auto pr1"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
